db.system: informix
db.driver: com.informix.jdbc.IfxDriver

instances:
  - db.address: 9.46.251.113 #IP Address
    db.port: 9088 #Port on which DB is running
    db.serverName: ol_informix1410
    db.username: root
    db.password: SGFwcHlAZnlyZUBuZWhhMjAyMQ==
    db.name: InformixDB
    db.path: /opt/IBM/Informix_Software_Bundle

    #OTel properties:
    otel.service.name: InformixDB

    #Data collector properties:
    #Either use `poll.interval` or `custom.poll.interval`
    poll.interval: 30
#    custom.poll.interval:
#      high: 10 #polling_value_in_sec
#      medium: 120 #polling_value_in_sec
#      low: 300 #polling_value_in_sec
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317
    #Custom Input
    custom.input:
      db.names: 'testDb1, testDb2, testDb3' # Provide the DB Names in Comma separated way

