llm.platform: watsonx
llm.application: llm-dc
server.address: bam-api.res.ibm.com
server.port: 443
server.scheme: https

instances:
  - otel.backend.url: http://localhost:4317
    otel.service.name: WatsonxDC
    price.prompt.tokens.per.kilo: 0.3
    price.complete.tokens.per.kilo: 0.3
